# Generated by Django 4.0.2 on 2022-04-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcherapp', '0003_remove_vacancy_year_in_school_vacancy_years_in_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='level_english',
            field=models.CharField(blank=True, choices=[('Elementary', 'Elementary'), ('Pre-Intermediate', 'Pre-Intermediate'), ('Upper-Intermediate', 'Upper-Intermediate'), ('Advanced', 'Advanced'), ('Proficiency', 'Proficiency')], default='Elementary', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='years_in_work',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('Intern', 'Intern'), ('Junior', 'Junior'), ('Middle', 'Middle'), ('Senior', 'Senior')], default='Intern', null=True),
        ),
    ]
