# Generated by Django 4.0.2 on 2022-04-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcherapp', '0004_alter_vacancy_level_english_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='level_english',
            field=models.CharField(blank=True, choices=[('Elementary', 'Elementary'), ('Pre-Intermediate', 'Pre-Intermediate'), ('Intermediate', 'Intermediate'), ('Upper-Intermediate', 'Upper-Intermediate'), ('Advanced', 'Advanced'), ('Proficiency', 'Proficiency')], default='Elementary', max_length=50, null=True),
        ),
    ]
