# Generated by Django 4.0.2 on 2022-05-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcherapp', '0007_startup'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='mail_address',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
