# Generated by Django 4.0.2 on 2022-05-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcherapp', '0008_startup_mail_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
